version: '3.8'

services:
  postgres:
    image: postgres
    container_name: pid_tuner
    environment:
      POSTGRES_DB: pid_tuner
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"